### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jhoogeboom** [Springest/alfred-asana-tasks#1]
Doesn't seem to work with me, the asanaconfig command does take my API-key, but then nothing happens when I press a or type anything thereafter.

**Comment by rickydazla** [comment]
same here

**Comment by ghost** [comment]
same

**Comment by lizgene** [comment]
Hey @jhoogeboom @ryne661 @rickydazla super late to the party, but as you may have guessed, we're no longer maintaining this repository. Thanks for checking it out, and definitely let me know if you'd like to take it over!
